# Generated by Django 5.2.13 on 2026-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_audio_file_album_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=255),
        ),
    ]
