# Generated by Django 5.2.13 on 2026-07-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='album_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lyrics', to='music.album'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='track_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lyrics', to='music.track'),
        ),
    ]
