# Generated by Django 5.2.13 on 2026-07-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_lyrics_album_ref_alter_lyrics_track_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='album_ref',
        ),
    ]
