# Generated by Django 5.2.13 on 2026-07-08 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_remove_lyrics_album_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lyrics',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='lyrics',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
