# Generated by Django 5.2.13 on 2026-07-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_lyrics_options_lyrics_added_at_alter_lyrics_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('youtube_video_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('views', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('podcast', 'Podcast'), ('interview', 'Interview'), ('breakdown', 'Album Breakdown'), ('live', 'Live'), ('reaction', 'Reaction'), ('documentary', 'Documentary')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
    ]
