# Generated by Django 5.2.13 on 2026-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(max_length=100),
        ),
    ]
